.TH MUCK "1" "December 2021"
.schar \[u2026] ...
.SH NAME
muck \- music player
.
.SH SYNOPSIS
.
.RB muck
.RI  [ OPTION ]...
.RI  [ URL ]...
.
.SH DESCRIPTION
.B muck
is a terminal music player built on top of FFmpeg.
.
.PP
When
.IR URL s
are given, they are used to populate
.B master
playlist.
.PP
When no URLs are given and standard input does not refer to a terminal, a
special
.B stdin
playlist is created and playlist file is read from the standard input.
.PP
Otherwise a
.B \.
playlist is created and files are read from the current directory.
.
.SS Playlists
.PP
Files ending in
.RB {\  .m3u " | " .m3u8 " | " .pl " }[ " .bz " | " .bz2 " | " .gz " | " .lz4 " | " .xz " | " .zst \ ]
are treated as (compressed) playlist files.
.PP
If file starts with
.BR #EXTM3U ,
it is recognized as an M3U playlist and for every media URL metadata is
written to and read from
.BR #EXTINF \ directive.
Playlists containing unknown comments are marked read-only thus never
overwritten.
.PP
.BI #PLAYLIST: NAME
directive can be used to provide a pretty name for a playlist (instead of
referencing to it by its path).
.PP
Playlists are opened only once, immediately after startup and may be nested
without limits.
.PP
Directories are treated like a virtual playlist with the limitation that they
are recognized on the command-line only, i.e. they are neither scanned
recursively nor can be played from a playlist. If you would like to overcome
this limitation, use
.BR "find | muck" .
.
.SS "Cover art"
Cover art is written to
.RB $ MUCK_COVER .
If not set, a suitable location is chosen.
.
.SH OPTIONS
.TP
.BI \-q\  QUERY
Execute initial search query.
.
.TP
.BI \-e\  COMMAND
Execute
.I COMMAND
at startup. Default:
.BR s " (begin playing from the first file)."
.
.TP
.BI \-a\  FILTERGRAPH
Specify filtergraph to use. See
.BR ffplay (1)
.BR -af .
.IP
Default:
.BR volume=replaygain=track .
Use
.B anull
to disable.
.
.TP
.BI \-c\  CODEC
Set output codec. Default:
.BR pcm " (fake codec that uses sample format of input)."
.
.TP
.BI \-f\  FORMAT
Set output format. Default:
.BR alsa .
.
.TP
.BI \-n\  FILENAME
Set output filename. Default: (none).
.
.TP
.BI \-m\  SIZE
Set maximum demuxer buffer size in kB. Default:
.BR 4096 .
.
.TP
.BI \-C\  SPEC
Specify column layout. Default:
.BR iy30a,x25A+Fd*20Tn*40t+f+vlgbIB*LCom*z .
.IP
.IR SPEC " := [ [" MODIFIER "] [" WIDTH "] " KEY " ]..."
.IP
.TS
tab(|)[allbox];
ll.
\fIMODIFIER\fR|Description
\[u2423]|Join with " ".
\fB*\fR|Make column flexible. \fIWIDTH\fR specifies minimum width.
\fB+\fR|Wrap in " (\[u2026])".
\fB,\fR|Join with ";".
\fB-\fR|Join with " - ".
\fB/\fR|Join with " / ".
.TE
.IP
.I WIDTH
specifies required column width. When omitted a default value is used. As a
special case, 0 means key should not be columnized but join it to the previous
column.
.IP
.I KEY
is a single letter metadata key. The complete list of recognized keys is
available in search mode.
.
.TP
.BI \-v
Print version information and exit.
.
.SH KEYBINDINGS
.SS "Live mode"
.TP
.BR 0-9
Set
.IR N
for next command.
.
.TP
.BR p ,\  N ,\  Up
Seek to
.IR N "th (default: 1) previous file."
.
.TP
.BR n ,\  Down
Seek to
.IR N "th (default: 1) next file."
.
.TP
.BR g ,\  Home
Seek to
.IR N "=MMSS (default: 0)."
.IP
For example
.BR 100g ,\  60g
both seek to 1 minute.
.
.TP
.BR G ,\  End
Seek to
.IR N "% (default: 1/\[*F]\[S2]\[~=]3/8=37.5%)"
in the file.
.
.TP
.BR s
Seek to
.IR N "th (default: 0) file."
.
.TP
.BR r
Seek to a random file (other than the currently playing file).
.
.TP
.BR Return
Seek again.
.
.TP
.BR j ,\  k
Seek by 5% but at least 5 seconds.
.
.TP
.BR h ,\  l ,\  Left ,\  Right
Seek by 5 seconds.
.
.TP
.BR .
Pause playback.
.
.TP
.BR > ,\  c
Unpause playback.
.
.TP
.B Space
Toggle pause playback.
.
.TP
.B M
Dump detailed metadata information about currently playing file into messages.
.
.TP
.BR / ,\  =
Search. Further help is part of the search screen.
.
.TP
.BR + ,\ \-
Change
.B volume
property of
.B volume
filter by +1% and -2% respectively.
.
.TP
.BR *
Toggle mute. Uses
.B volume
filter.
.
.TP
.BR H ,\  L ,\  Shift+Left ,\  Shift+Right
Scroll file list horizontally.
.
.TP
.B v
Switch between
.B live
and
.B visual
modes. Live mode is the default.
.
.TP
.B m
Show messages.
.
.TP
.BR Ctrl+L
Refresh screen.
.
.TP
.BR Z ,\  Q ,\  q ,\  F10
Quit.
.
.TP
.BR ? ,\  F1
Open manual.
.
.TP
(other letter)
Execute
.RB $ MUCK_HOME/{KEY} .
.IP
.RB $ MUCK_ *
environment variables are set, based on the currently playing file.
.
.SS "Visual mode"
.TP
.BR p ,\  N ,\  Up ,\  n ,\  Down ,\  g ,\  Home ,\  G ,\  End ,\  s ,\  r ,\  / ,\  =
Same as in live mode but do not start playing.
.
.TP
.BR Return
Start playing current file.
.
.TP
.BR j ,\  k
Move selection.
.
.TP
(other)
Same as in live mode.
.
.SH ENVIRONMENT
.TP
.B EDITOR
Editor to use for text-editing operations.
.
.TP
.B MUCK_HOME
Configuration home.
.IP
Always set for children.
.
.SH EXAMPLE
.
.IP \(bu
Read files from arguments:
.sp
.EX
$ muck i-scream.flac http://online-screams.com:8008/radio ~/Music ~/Downloads
.EE
.
.IP \(bu
Read playlist file from standard input:
.sp
.EX
$ muck <<"PLAYLIST"
#EXTM3U
#EXTINF:title="foobar",
# This is my favourite song:
i-scream.flac
http://online-screams.com:8008/radio
~/mus
~/Music
PLAYLIST
.EE
.
.SH "SEE ALSO"
.BR ffmpeg (1)
.BR ffplay (1)
.
.SH AUTHORS
Written by zsugabubus.
.
.SH LICENSE
GPLv3+
