.TH MUCK "1" "August 2021"
.SH NAME
muck \- music player
.
.SH SYNOPSIS
.
.RB muck
.RI  [ OPTION ]...
.RI  [ URL ]...
.
.SH DESCRIPTION
.B muck
is a terminal music player built on top of FFmpeg.
.
.PP
When
.IR URL s
are given, they are used to populate
.B master
playlist.
.PP
When no URLs are given and standard input does not refer to a terminal, a
special
.B stdin
playlist is created and playlist file is read from the standard input.
.PP
Otherwise a
.B \.
playlist is created and files are read from the current directory.
.
.SS Playlists
.PP
Files ending in
.RB {\  .m3u " | " .m3u8 " | " .pl " }[ " .bz " | " .bz2 " | " .gz " | " .lz4 " | " .xz " | " .zst \ ]
are treated as (compressed) playlist files.
.PP
If file starts with
.BR #EXTM3U ,
it is recognized as an M3U playlist and for every media URL metadata is
written to and read from
.BR #EXTINF \ directive.
Playlists containing unknown comments are marked read-only thus never
overwritten.
.PP
.BI #PLAYLIST: NAME
directive can be used to provide a pretty name for a playlist (instead of
referencing to it by its path).
.PP
Playlists are opened only once, immediately after startup and may be nested
without limits.
.PP
Directories are treated like a virtual playlist with the limitation that they
are recognized on the command-line only, i.e. they are neither scanned
recursively nor can be played from a playlist. If you would like to overcome
this limitation, use
.BR "find | muck" .
.
.SS "Cover art"
When
.RB $ MUCK_HOME/cover
exists, cover art of currently playing file is written to it.
.PP
Note that it can be a symbolic link (e.g. \[->] /tmp/cover), just be aware that
some image viewers can detect file time changes on their real path only.
.
.SH OPTIONS
.TP
.BI \-q\  QUERY
Execute initial search query.
.
.TP
.BI \-x\  COMMAND
Execute
.I COMMAND
at startup.
.IP
Default:
.B s
(begin playing from the first file).
.
.TP
.BI \-a\  FILTERGRAPH
Specify filtergraph to use. See
.BR ffplay (1)
.BR -af .
.IP
Default:
.BR volume=replaygain=track .
Use
.B anull
to disable.
.
.TP
.BI \-c\  CODEC
Output codec.
.IP
Default:
.B pcm
(fake codec that uses sample format of input).
.
.TP
.BI \-o\  FORMAT
Output format.
.IP
Default:
.BR alsa .
.
.TP
.BI \-n\  FILENAME
Output filename.
.IP
Default:
(none).
.
.TP
.BI \-m\  SIZE
Maximum demuxer buffer size in kB.
.IP
Default:
.BR 8192 .
.
.TP
.BI \-w
Allow writing
.B user.last_play
extended attributes.
.
.TP
.B \-d
Print debug information. Be very verbose when given twice.
.
.SH USAGE
.SS Keybindings
.TP
.BR 0-9 ,\ \-
Set
.IR N x
for next command.
.
.TP
.BR p ,\  N
Seek to
.IR Nn "-th (default: 1)"
previous file.
.
.TP
.BR n
Seek to
.IR Nn -th
next file. (Default seek command at startup.)
.
.TP
.BR s
Seek to
.IR Ns "\-th (default: 0) file."
.
.TP
.BR r
Seek to a random file.
.
.TP
.BR Return
Seek again.
.
.TP
.BR g
Seek to
.IR Ng " (default: 0)"
seconds.
.
.TP
.BR G
Seek to
.IR NG "% (default: 1/\[*F]\[S2]\[~=]3/8=37.5%)"
in the file.
.
.TP
.BR h ,\  l
Seek by 5 seconds.
.
.TP
.BR j ,\  k
Seek by 5% but at least 5 seconds.
.
.TP
.BR .
Pause playback.
.
.TP
.BR > ,\  c
Unpause playback.
.
.TP
.B Space
Toggle pause playback.
.
.TP
.B i
Print information about currently playing file.
.
.TP
.BR w here
Print files around currently playing file.
.
.TP
.BR I ,\  W
Toggle automatic
.BR i " or " w
whenever seeking in playlist.
.
.TP
.B m
Print detailed metadata information about currently playing.
.
.TP
.BR / ,\  =
Search.
.IP
Detailed manual is part of the search screen.
.
.TP
.BR + ,\ \-
Change volume property of
.B volume
filter by +1% and -2% respectively.
.
.TP
.BR *
Toggle mute. Uses
.B volume
filter.
.
.TP
.B S
Print statistics.
.
.TP
.BR Z ,\  Q ,\  q
Quit.
.
.TP
.BR Escape
Ignore.
.
.TP
(other letter)
Execute
.RB $ MUCK_HOME/{KEY} .
.IP
.RB $ MUCK_ *
environment variables are set, based on the currently playing file.
.
.SH ENVIRONMENT
.TP
.B EDITOR
Editor to use for text-editing operations.
.
.TP
.B MUCK_HOME
Configuration root directory.
.IP
Always set for executed programs.
.IP
Default:
.RB $ HOME /.config/muck.
.
.SH EXAMPLE
.
.IP \(bu
Read files from arguments:
.sp
.EX
$ muck i-scream.flac http://online-screams.com:8008/radio ~/Music ~/Downloads
.EE
.
.IP \(bu
Read playlist file from standard input:
.sp
.EX
$ muck <<"PLAYLIST"
#EXTM3U
#EXTINF:title="foobar",
# This is my favourite song:
i-scream.flac
http://online-screams.com:8008/radio
~/mus
~/Music
PLAYLIST
.EE
.
.SH "SEE ALSO"
.BR ffmpeg (1)
.BR ffplay (1)
.BR realpath (1)
.
.SH AUTHORS
Written by zsugabubus.
.
.SH LICENSE
GPLv3+
