.TH MUCK "1" "December 2021"
.schar \[u2026] ...
.SH NAME
muck \- music player
.
.SH SYNOPSIS
.
.RB muck
.RI  [ OPTION ]...
.RI  [ URL ]...
.
.SH DESCRIPTION
.B muck
is a terminal music player built on top of FFmpeg.
.
.PP
.B master
playlist is populated with the given
.IR URL s.
When no URLs are given and standard input does not refer to a terminal, a
special
.B stdin
playlist is created and playlist file is read from the standard input.
Otherwise a
.B \.
playlist is created and files are read from the current directory.
.
.SS Playlists
.PP
URLs ending in
.RB {\  .m3u " | " .m3u8 " | " .pl " }[ " .bz " | " .bz2 " | " .gz " | " .lz4 " | " .xz " | " .zst \ ]
are treated as (compressed) playlist files.
.PP
Playlist files that start with
.BR #EXTM3U ,
are recognized as M3U playlists and for every media URL metadata is
written to and read from the
.BR #EXTINF \ directive.
Playlists containing unknown comments are marked read-only thus never
overwritten.
.PP
.BI #PLAYLIST: NAME
directive can be used to give a pretty name for a playlist (instead of
referencing to it by its path).
.PP
Playlists are opened once at startup and may be nested without limits.
.PP
Directories are treated like a virtual playlist with the limitation that they
are recognized on the command-line only, i.e. they are neither scanned
recursively nor can be played from inside a playlist. If you would like to
overcome this limitation, use
.BR "find -type f | muck" .
.
.SS Cover art
Cover art is written to
.RB $ MUCK_COVER .
If not set, a suitable location is chosen.
.
.SH OPTIONS
.TP
.BI \-q\  QUERY
Execute initial search query.
.
.TP
.BI \-e\  COMMAND
Execute
.I COMMAND
at startup. Default:
.BR s " (begin playing from the first file)."
.
.TP
.BI \-a\  FILTERGRAPH
Specify filtergraph to use. See
.BR ffplay (1)
.BR -af .
.IP
Default:
.BR volume=replaygain=track .
Use
.B anull
to disable.
.
.TP
.BI \-c\  CODEC
Set output codec. Default:
.BR pcm " (fake codec that uses sample format of input)."
.
.TP
.BI \-f\  FORMAT
Set output format. Default:
.BR alsa .
.
.TP
.BI \-o\  FILENAME
Set output filename. Default: (none).
.
.TP
.BI \-m\  SIZE
Set maximum demuxer buffer size in kB. Default:
.BR 4096 .
.
.TP
.BI \-C\  SPEC
Specify column layout. Default:
.BR iy30a,x25A+Fd*20Tn*40t+f+vlgbIB*LCoOm*z .
.IP
.IR SPEC " := [ [" MODIFIER "] [" WIDTH "] " KEY " ]..."
.IP
.TS
tab(|)[allbox];
lil
ll
lbl.
MODIFIER|Description
\[u2423]|Join with " ".
*|Make column flexible. \fIWIDTH\fR specifies minimum width.
+|Wrap in " (\[u2026])".
,|Join with ";".
-|Join with " - ".
/|Join with " / ".
.TE
.IP
.I WIDTH
specifies required column width. When omitted a default value is used. As a
special case, 0 means key should not be columnized but join it to the previous
column.
.IP
.I KEY
is a single letter metadata key. The complete list of recognized keys is
available in search mode.
.
.TP
.BI \-v
Print version information and exit.
.
.SH KEYBINDINGS
.SS Live mode
.TP
.BR 0-9
Set
.IR N
for next command.
.
.TP
.BR p ,\  N ,\  Up
Seek to
.IR N "th (default: 1) previous file."
.
.TP
.BR n ,\  Down
Seek to
.IR N "th (default: 1) next file."
.
.TP
.BR s
Seek to
.IR N "th (default: 0) file."
.
.TP
.BR r
Seek to a random file (other than the currently playing file).
.
.TP
.BR g ,\  Home
Seek to
.IR N "=MMSS (default: 0)."
.IP
For example
.BR 100g ,\  60g
both seek to 1 minute.
.
.TP
.BR G ,\  End
Seek to
.IR N "% (default: 1/\[*F]\[S2]\[~=]3/8=37.5%)"
in the file.
.
.TP
.BR j ,\  k
Seek by 5% but at least 5 seconds.
.
.TP
.BR h ,\  l ,\  Left ,\  Right
Seek by 5 seconds.
.
.TP
.BR Return
Seek again. Seek command to be repeated is displayed in the status line.
.
.TP
.BR + ,\  \-
Change
.B volume
property of
.B volume
filter by +1% and -2%, respectively.
.
.TP
.BR *
Set volume to
.I N
if given, otherwise toggle mute. Uses
.B volume
filter.
.
.TP
.BR .
Pause playback.
.
.TP
.BR > ,\  c
Unpause playback.
.
.TP
.B Space
Toggle pause playback.
.
.TP
.BR t
Switch audio track. When multiple tracks are available it is show in the status
line.
.
.TP
.BR O
Toggle show stream information.
.
.TP
.BR / ,\  =
Search.
.
.TP
.B |
Print files to standard output.
.
.TP
.B v
Switch between live and visual modes. Live mode is the default.
.
.TP
.BR H ,\  L ,\  Shift+Left ,\  Shift+Right
Scroll file list horizontally.
.
.TP
.B w
Toggle column widening. Ignore narrow columns (\[<=]10 cells).
.
.TP
.B M
Dump detailed metadata information about currently playing file to standard
error.
.
.TP
.BR Ctrl+L
Refresh screen.
.
.TP
.BR Z ,\  Q ,\  q ,\  F10
Quit.
.
.TP
.BR ? ,\  F1
Open manual.
.
.TP
(other letter)
Execute
.RB $ MUCK_HOME/{KEY} .
.IP
.RB $ MUCK_ *
environment variables are set, based on the currently playing file.
.
.SS Visual mode
.TP
.BR p ,\  Down ,\  N ,\  n ,\  Up ,\  s ,\  r ,\  / ,\  =
Same as in live mode but do not start playing.
.
.TP
.BR Return
Start playing current file.
.
.TP
.BR j ,\  k
Move selection by
.I N
(default: 1).
.
.TP
.BR g ,\  Home
Go to top.
.
.TP
.BR G ,\  End
Go to bottom.
.
.TP
(other)
Same as in live mode.
.
.SH SEARCH
.I FIRST-LINE
:=
.I EXPR
.br
.
.I EXPR
:=
.RI [ KEY ]...
[ "?" ] [ { "<" | ">" }[ "=" ] | "~" ]
.RI [ VALUE ]
.
.br
.I EXPR
:=
.I EXPR
"&"
.I EXPR
|
.I EXPR
.I EXPR
.
.br
.I EXPR
:=
.I EXPR
"|"
.I EXPR
.
.br
.I EXPR
:= "!"
.I EXPR
.
.br
.I VALUE
:=
.I QUOTED
|
.I WORD
.
.br
.I QUOTED
:= "'" [ all characters - "'" ]... "'"
.
.br
.I QUOTED
:= '"' [ all characters - '"' ]... '"'
.
.br
.I WORD
:= { all characters - "'", '"', " ", "|", ")" } [ all characters - " ", "|", ")" ]...
.
.P
Tokens may be separated by " " (space).
.
.P
"~" tests whether given PCRE
.RI ( VALUE )
matches
.IR KEY .
May be omitted since it is the default.
.IP
.TS
tab(@)[];
lbl.
t[0-9]+cent@Same as "t~[0-9]cent".
ftcent@Same as "ftcent~" not "ft~cent".
t'oast for breakfast'@Can be omitted since "'" makes it clear.
'oast for breakfast'@Detto but without keys specified.
.TE
.
.P
"<", ">", "=" compares pairs of integers. All non-digits are ignored in
between.
.IP
.TS
tab(@)[];
lbl.
y<'show tracks before 2001.02.03. please'@Matches "2000", "2000-04.10", "2001X02".
y<=2001.02.03@Also matches "2001 02 03".
o~flac o>44@High-resolution FLAC files.
n?=3@Third tracks.
.TE
.
.P
If
.I KEY
is omitted it defaults to keys marked with "+". In practice, it means almost
all known metadata in order to ease search of unscanned files. The exact list
is shown in the search screen, though it is rarely interesting.
.IP
.TS
tab(@)[];
lbl
lb^
lb^.
~love.*bugs@Searches artist, title, url, comment...
'all star'
<=1001
.TE
.
.P
When multiple
.IR KEY s
are specified it matches when any of them is matching.
.IP
.TS
tab(@)[];
lbl.
axf^Don@Same as "a^Don | x^Don | f^Don".
.TE
.
.P
If
.I VALUE
is omitted it is taken from the currently playing file.
For
.IR KEY s
with muliplicity (separated by ";") only the first occurence is considered.
.IP
.TS
tab(@)[];
lbl.
T@Tracks from the currently playing album.
y A T@A bit more specific.
A@Same as A~'Good' when currently playing file has A='Good;Bad;Ugly'.
.TE
.
.P
.I VALUE
is matched caseless unless it contains uppercase letter (smartcase).
.IP
.TS
tab(@)[];
lbl.
t~ear@Case-insensitive; matches "EAR", "eAR", "Ear" and "Heart".
t~Ear@Case-sensitive; matches "Ear" only.
.TE
.
.P
If file has no tags (either because not scanned yet or does not have at all),
.IR KEY s
marked with "+" match
.I VALUE
against URL. This behavior can be prevented by "?" that requires
.I KEY
to be present.
.IP
.TS
tab(@)[];
lbl.
a~jimmy t~sunshine@Returns unscanned file named 'Jimmy - Sunshine.mp3'.
a?jimmy@Would not return the one above.
n?.@Use "." (match any) after "?" to test whether key is set.
.TE
.
.P
Between expressions "!", "&", "|" can be used to express
"negation", "and" and "or" operations, respectively. "&" is the
default so it may be omitted. "(", ")" can be used for
grouping.
.IP
.TS
tab(@)[];
lb l.
!(g~rock y<2000)@All but rock before 2000.
!(g~rock & y<2000)@Same but "&" is explicitly written.
!g~rock | (( (y>2000)| y=2000))@Same.
v~(bla)@Syntax error.
v~(bla )@Regex syntax error.
v~(b|a)@Regex syntax error + syntax error.
v~'(bla)'@Correct.
v~'(b|a)'@Correct.
(v'mix\\)')@Matches version containing "mix)".
.TE
.
.SH ENVIRONMENT
.TP
.B EDITOR
Editor to use for text-editing operations.
.
.TP
.B MUCK_HOME
Configuration home.
.IP
Always set for children.
.
.SH EXAMPLES
.
Read files from arguments.
.IP
.EX
muck i-scream.flac http://online-screams.com:8008/radio ~/Music ~/Downloads
.EE
.
.P
Read playlist from standard input.
.IP
.EX
muck <<"PLAYLIST"
#EXTM3U
#EXTINF:title="foobar",
# This is my favourite song:
i-scream.flac
http://online-screams.com:8008/radio
/home/user/Music
/home/user/Downloads
PLAYLIST
.EE
.
.P
Start random playing matching files with decreased volume.
.IP
.EX
muck -q '~"b u g"' -e '80*r'
.EE
.
.P
Print errors.
.IP
.EX
muck 2>>/tmp/err
.EE
.
.P
An energy-efficient setup: Disable software volume and let ALSA talk directly
to hardware. When run in an XTerm-compatible terminal emulator screen is not
updated when unfocused.
.IP
.EX
muck -f alsa -o hw -a anull -e Os
.EE
.
.P
Using together with
.BR alsaequal .
.IP
.EX
muck -f alsa -c pcm_f32le -a anull -e Os
.EE
.
.SH "SEE ALSO"
.BR ffmpeg (1),
.BR ffplay (1),
.BR pcre2syntax (1)
.
.SH AUTHORS
Written by zsugabubus.
.
.SH LICENSE
GPLv3+
